# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\trpc.proto\x12\x03rpc\"\x19\n\tRARequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\x07RAReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06report\x18\x02 \x01(\t\"8\n\nKeyRequest\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03key\x18\x03 \x03(\x0c\"\x1b\n\x08KeyReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x02 \x01(\t\"+\n\nQueryReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2\xb2\x01\n\tOpaqueRPC\x12\x35\n\x13relayGenerateReport\x12\x0e.rpc.RARequest\x1a\x0c.rpc.RAReply\"\x00\x12:\n\x16relayFinishAttestation\x12\x0f.rpc.KeyRequest\x1a\r.rpc.KeyReply\"\x00\x12\x32\n\nrelayQuery\x12\x11.rpc.QueryRequest\x1a\x0f.rpc.QueryReply\"\x00\x62\x06proto3'
)




_RAREQUEST = _descriptor.Descriptor(
  name='RARequest',
  full_name='rpc.RARequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc.RARequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=43,
)


_RAREPLY = _descriptor.Descriptor(
  name='RAReply',
  full_name='rpc.RAReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='rpc.RAReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='report', full_name='rpc.RAReply.report', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=87,
)


_KEYREQUEST = _descriptor.Descriptor(
  name='KeyRequest',
  full_name='rpc.KeyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='rpc.KeyRequest.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='rpc.KeyRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='rpc.KeyRequest.key', index=2,
      number=3, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=145,
)


_KEYREPLY = _descriptor.Descriptor(
  name='KeyReply',
  full_name='rpc.KeyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='rpc.KeyReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=174,
)


_QUERYREQUEST = _descriptor.Descriptor(
  name='QueryRequest',
  full_name='rpc.QueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='rpc.QueryRequest.query', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=205,
)


_QUERYREPLY = _descriptor.Descriptor(
  name='QueryReply',
  full_name='rpc.QueryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='rpc.QueryReply.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='rpc.QueryReply.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=250,
)

DESCRIPTOR.message_types_by_name['RARequest'] = _RAREQUEST
DESCRIPTOR.message_types_by_name['RAReply'] = _RAREPLY
DESCRIPTOR.message_types_by_name['KeyRequest'] = _KEYREQUEST
DESCRIPTOR.message_types_by_name['KeyReply'] = _KEYREPLY
DESCRIPTOR.message_types_by_name['QueryRequest'] = _QUERYREQUEST
DESCRIPTOR.message_types_by_name['QueryReply'] = _QUERYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RARequest = _reflection.GeneratedProtocolMessageType('RARequest', (_message.Message,), {
  'DESCRIPTOR' : _RAREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RARequest)
  })
_sym_db.RegisterMessage(RARequest)

RAReply = _reflection.GeneratedProtocolMessageType('RAReply', (_message.Message,), {
  'DESCRIPTOR' : _RAREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.RAReply)
  })
_sym_db.RegisterMessage(RAReply)

KeyRequest = _reflection.GeneratedProtocolMessageType('KeyRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEYREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.KeyRequest)
  })
_sym_db.RegisterMessage(KeyRequest)

KeyReply = _reflection.GeneratedProtocolMessageType('KeyReply', (_message.Message,), {
  'DESCRIPTOR' : _KEYREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.KeyReply)
  })
_sym_db.RegisterMessage(KeyReply)

QueryRequest = _reflection.GeneratedProtocolMessageType('QueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.QueryRequest)
  })
_sym_db.RegisterMessage(QueryRequest)

QueryReply = _reflection.GeneratedProtocolMessageType('QueryReply', (_message.Message,), {
  'DESCRIPTOR' : _QUERYREPLY,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:rpc.QueryReply)
  })
_sym_db.RegisterMessage(QueryReply)



_OPAQUERPC = _descriptor.ServiceDescriptor(
  name='OpaqueRPC',
  full_name='rpc.OpaqueRPC',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=253,
  serialized_end=431,
  methods=[
  _descriptor.MethodDescriptor(
    name='relayGenerateReport',
    full_name='rpc.OpaqueRPC.relayGenerateReport',
    index=0,
    containing_service=None,
    input_type=_RAREQUEST,
    output_type=_RAREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='relayFinishAttestation',
    full_name='rpc.OpaqueRPC.relayFinishAttestation',
    index=1,
    containing_service=None,
    input_type=_KEYREQUEST,
    output_type=_KEYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='relayQuery',
    full_name='rpc.OpaqueRPC.relayQuery',
    index=2,
    containing_service=None,
    input_type=_QUERYREQUEST,
    output_type=_QUERYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OPAQUERPC)

DESCRIPTOR.services_by_name['OpaqueRPC'] = _OPAQUERPC

# @@protoc_insertion_point(module_scope)
